name: Deploy Infra

on: workflow_dispatch

env:
  AWS_REGION: us-east-2
  IAM_ROLE: arn:aws:iam::160071257600:role/david-vasconcelos-iac-lab-github-actions-role

jobs:
  Terraform-Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    defaults:
      run:
        working-directory: session-6

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-session-name: GitHubActionsSession
          role-to-assume: ${{ env.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get aws identity
        run: |
          aws sts get-caller-identity            

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
      
      - name: Terraform Init Backend
        id: init
        run: terraform init -input=false

      - name: Write tfvars file
        run: |
          cat <<EOF > dev.tfvars
          region                    = "us-east-2"
          vpc_cidr                  = "192.168.1.0/25"
          number_of_public_subnets  = 2
          number_of_private_subnets = 2
          number_of_secure_subnets  = 2
          db_username               = "db_admin_user"
          EOF
      
      - name: Terraform Plan
        id: backend_plan
        run: terraform plan -var-file="dev.tfvars"
        continue-on-error: false
      
      - name: Terraform Apply
        id: backend_apply
        run: terraform apply -auto-approve -var-file="dev.tfvars"       
        continue-on-error: false

    

       
