name: Deploy Infra

on: 
  workflow_dispatch:
    inputs:
      aws_role:
        description: 'AWS Role to assume'
        required: true
        type: string
      aws_region:
        description: 'Select region'
        required: true
        type: choice
        options:
          - us-east-2
          - ap-southeast-2         

permissions:
  id-token: write
  contents: read

jobs:
  Terraform-Deploy:    
    runs-on: ubuntu-latest
    env:
      TF_VAR_region: ${{ inputs.aws_region }}
      TF_VAR_vpc_cidr: ${{ vars.vpc_cidr }}
      TF_VAR_number_of_public_subnets: ${{ vars.number_of_public_subnets }}
      TF_VAR_number_of_private_subnets: ${{ vars.number_of_private_subnets }}
      TF_VAR_number_of_secure_subnets: ${{ vars.number_of_secure_subnets }}      

    defaults:
      run:
        working-directory: session-6

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-session-name: GitHubActionsSession
          role-to-assume: ${{ inputs.aws_role }}
          aws-region: ${{ inputs.aws_region }}

      - name: Get aws identity
        run: |
          aws sts get-caller-identity            

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
      
      - name: Terraform Init Backend
        id: init
        run: terraform init     
      
      - name: Terraform Plan
        id: backend_plan
        run: terraform plan       
        continue-on-error: false
      
      - name: Terraform Apply
        id: backend_apply
        run: |
          terraform apply -auto-approve 
        continue-on-error: false

    

       
